import streamlit as st
from PIL import Image
st.title("스포츠에 관하여")
st.write("여가 활동이나 경기, 체력 단련을 위하여 하는 신체 운동. 육상 경기·수영·각종 구기·스키·스케이트·등산 등의 총칭. 순화어는 `운동'")

st.markdown("# 종류\n스포츠 종류에 대해 알아보자")

st.image('https://sokorea.or.kr/img/sport1.png',caption="플로어하키", width=300)
st.image('https://sokorea.or.kr/img/sport2.png')
st.image('https://sokorea.or.kr/img/sport3.png')
st.image('https://sokorea.or.kr/img/sport4.png')
st.image('https://sokorea.or.kr/img/sport5.png')
st.image('https://sokorea.or.kr/img/sport6.png')
st.image('https://sokorea.or.kr/img/sport7.png')
st.image('https://sokorea.or.kr/img/sport8.png')
st.image('https://sokorea.or.kr/img/sport9.png')
st.image('https://sokorea.or.kr/img/sport10.png')
st.image('https://sokorea.or.kr/img/sport11.png')
st.image('https://sokorea.or.kr/img/sport12.png')
st.image('https://sokorea.or.kr/img/sport13.png')
st.image('https://sokorea.or.kr/img/sport14.png')
st.image('https://sokorea.or.kr/img/sport15.png')
st.image('https://sokorea.or.kr/img/sport16.png')
st.image('https://sokorea.or.kr/img/sport17.png')
st.image('https://sokorea.or.kr/img/sport18.png')
st.image('https://sokorea.or.kr/img/sport19.png')
st.image('https://sokorea.or.kr/img/sport20.png')
st.image('https://sokorea.or.kr/img/sport21.png')
st.image('https://sokorea.or.kr/img/sport22.png')
st.image('https://sokorea.or.kr/img/sport23.png')
st.image('https://sokorea.or.kr/img/sport24.png')
st.image('https://sokorea.or.kr/img/sport25.png')
st.image('https://sokorea.or.kr/img/sport26.png')
st.image('https://sokorea.or.kr/img/sport27.png')
st.image('https://sokorea.or.kr/img/sport28.png')
st.image('https://sokorea.or.kr/img/sport29.png')
st.image('https://sokorea.or.kr/img/sport30.png')
st.image('https://sokorea.or.kr/img/sport31.png')
st.image('https://sokorea.or.kr/img/sport32.png')
st.image('https://sokorea.or.kr/img/sport33.png')
st.image('https://sokorea.or.kr/img/sport34.png')
st.image('https://sokorea.or.kr/img/sport35.png')
